version: '2'
services:
  web:
    build: .
    volumes:
      - .:/code/
    environment:
      - PYTHONPATH=.
      - DJANGO_SETTINGS_MODULE=freechess.settings
    command: python ./freechess/manage.py runserver 0.0.0.0:5000
    ports:
      - "5000"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    ports:
      - "5432"
    environment:
      - POSTGRES_DB=freechessdb
      - POSTGRES_USER=freechess
      - POSTGRES_PASSWORD=freechess
      - PGPASSWORD=freechess
