web:
  build: .
  volumes:
    - .:/code/
  environment:
    - PYTHONPATH=.
    - DJANGO_SETTINGS_MODULE=freechess.settings
  command: bash -c "python ./freechess/manage.py migrate && python ./freechess/manage.py runserver 0.0.0.0:5000"
  ports:
    - "5000"
  links:
    - db
db:
  image: postgres:latest
  ports:
    - "5432"
  environment:
    - USER=postgres
    - DB=postgres
